"""Pydantic request and response data-transfer objects."""

from silly_teamwork.schemas.admin import (
    AdminActionResponse,
    AdminGlobalInviteResponse,
    AdminTeamResponse,
    AdminUserResponse,
)
from silly_teamwork.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from silly_teamwork.schemas.file import (
    FileIndexItemResponse,
    FileIndexProjectResponse,
    FileIndexTaskResponse,
    FileIndexTeamResponse,
    FileIndexUploaderResponse,
    FileListItemResponse,
    FileMetadataUpdate,
    FilePermissionsResponse,
    FileResponse,
    ProjectFileIndexResponse,
    ProjectFileTaskGroupResponse,
)
from silly_teamwork.schemas.notification import (
    MarkAllNotificationsReadResponse,
    NotificationResponse,
)
from silly_teamwork.schemas.personal_task import (
    MyPersonalTaskResponse,
    PersonalTaskCreate,
    PersonalTaskCreateResponse,
    PersonalTaskDetailResponse,
    PersonalTaskProjectSummary,
    PersonalTaskSummaryResponse,
    PersonalTaskTeamSummary,
    TaskAssignmentResponse,
    TaskAssignmentUserResponse,
)
from silly_teamwork.schemas.project import (
    ProjectCreate,
    ProjectMemberAdd,
    ProjectMemberResponse,
    ProjectOwnerTransfer,
    ProjectResponse,
    ProjectStatusUpdate,
    ProjectUpdate,
)
from silly_teamwork.schemas.task import (
    TaskCreate,
    TaskMemberAdd,
    TaskMemberResponse,
    TaskOwnerTransfer,
    TaskResponse,
    TaskStatusUpdate,
    TaskUpdate,
)
from silly_teamwork.schemas.team import (
    InvitationCodeResponse,
    InvitationCreateRequest,
    InvitationRole,
    TeamCreateRequest,
    TeamDetailResponse,
    TeamJoinRequest,
    TeamMemberResponse,
    TeamResponse,
    TeamRoleResponse,
)
from silly_teamwork.schemas.user import PasswordChangeRequest, UserProfileUpdate, UserResponse

__all__ = [
    "AdminActionResponse",
    "AdminGlobalInviteResponse",
    "AdminTeamResponse",
    "AdminUserResponse",
    "FileMetadataUpdate",
    "FileResponse",
    "FileIndexItemResponse",
    "FileIndexProjectResponse",
    "FileIndexTaskResponse",
    "FileIndexTeamResponse",
    "FileIndexUploaderResponse",
    "FileListItemResponse",
    "FilePermissionsResponse",
    "InvitationCodeResponse",
    "InvitationCreateRequest",
    "InvitationRole",
    "LoginRequest",
    "MarkAllNotificationsReadResponse",
    "NotificationResponse",
    "PersonalTaskCreate",
    "PersonalTaskCreateResponse",
    "PersonalTaskDetailResponse",
    "PersonalTaskProjectSummary",
    "PersonalTaskSummaryResponse",
    "PersonalTaskTeamSummary",
    "MyPersonalTaskResponse",
    "ProjectCreate",
    "ProjectFileIndexResponse",
    "ProjectFileTaskGroupResponse",
    "ProjectMemberAdd",
    "ProjectMemberResponse",
    "ProjectOwnerTransfer",
    "ProjectResponse",
    "ProjectStatusUpdate",
    "ProjectUpdate",
    "PasswordChangeRequest",
    "RegisterRequest",
    "TeamCreateRequest",
    "TeamDetailResponse",
    "TeamJoinRequest",
    "TeamMemberResponse",
    "TeamResponse",
    "TeamRoleResponse",
    "TaskCreate",
    "TaskAssignmentResponse",
    "TaskAssignmentUserResponse",
    "TaskMemberAdd",
    "TaskMemberResponse",
    "TaskOwnerTransfer",
    "TaskResponse",
    "TaskStatusUpdate",
    "TaskUpdate",
    "TokenResponse",
    "UserResponse",
    "UserProfileUpdate",
]
